#!/bin/bash
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  CyberRange TZ — Ping Sweep Lab             ║"
echo "║  Module 2: Network Reconnaissance (Red Team) ║"
echo "╠══════════════════════════════════════════════╣"
echo "║                                              ║"
echo "║  Target Network : 10.0.0.0/24               ║"
echo "║  Your IP        : 10.0.0.10                 ║"
echo "║                                              ║"
echo "║  Intelligence reports 3 hosts at:            ║"
echo "║    10.0.0.2  —  Target Alpha                ║"
echo "║    10.0.0.3  —  Target Bravo                ║"
echo "║    10.0.0.4  —  Target Charlie              ║"
echo "║                                              ║"
echo "║  Objective: Determine which targets are      ║"
echo "║  alive using ping and fping only.            ║"
echo "║                                              ║"
echo "║  Tools: ping, fping, curl                    ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
