#!/bin/bash
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  CyberRange TZ — Detect ICMP Sweeps         ║"
echo "║  Module 2: Network Reconnaissance (Blue Team)║"
echo "╠══════════════════════════════════════════════╣"
echo "║                                              ║"
echo "║  Scenario: Your IDS captured suspicious      ║"
echo "║  network traffic on the 10.0.0.0/24 subnet.  ║"
echo "║                                              ║"
echo "║  Capture file: /var/log/capture.log          ║"
echo "║                                              ║"
echo "║  Objective: Analyze the capture, identify    ║"
echo "║  the attacker, and quantify the sweep.       ║"
echo "║                                              ║"
echo "║  Tools: tcpdump, grep, awk, wc               ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
